<?php

declare (strict_types=1);
namespace CresenityDevCloudAPMVendor\Cresenity\DevCloud\APM\Support;

/**
 * Random hex identifiers for internal correlation (e.g. BatchProcessor item ids,
 * ServiceResource instance id fallback). Not used for trace/span ids — those are
 * generated by the OpenTelemetry SDK itself (SPEC §58: don't invent an equivalent
 * of something the standard already provides).
 */
final class IdGenerator
{
    public static function hex(int $bytes = 16): string
    {
        return bin2hex(random_bytes($bytes));
    }
}
/**
 * Random hex identifiers for internal correlation (e.g. BatchProcessor item ids,
 * ServiceResource instance id fallback). Not used for trace/span ids — those are
 * generated by the OpenTelemetry SDK itself (SPEC §58: don't invent an equivalent
 * of something the standard already provides).
 */
\class_alias('CresenityDevCloudAPMVendor\Cresenity\DevCloud\APM\Support\IdGenerator', 'Cresenity\DevCloud\APM\Support\IdGenerator', \false);
